### ISSUE TITLE
Fix filemode implementation to work on windows

### ISSUE THREAD

**Issue by inconshreveable** [inconshreveable/go-update#13]

**Comment by abourget** [comment]
Don't know if this is related, but I get an error that I can't write to a file used by another process. Is there anything I must do to the executable the first time ? Must this lib be updated instead ?

**Comment by abourget** [comment]
I'm running as Administrator under Windows :-)

**Comment by inconshreveable** [comment]
There shouldn't be. This issue is separate and about writing the implementation so that unix systems can control what permissions are set on the updated file in a way that works on windows as well.

What you're describing is a different, so you should probably open a separate issue. That being said, the library is known to work properly on Windows. Please file a separate issue, if possible with a reproducible case and the exact error message encountered.

**Comment by inconshreveable** [comment]
This is resolved in the new API by essentially ignoring the problem. Instead of query for existing modebits via unix-only syscall, we use an explicit set of modebits for the update.

https://github.com/inconshreveable/go-update/pull/21
