### ISSUE TITLE
Fails to rename on Windows

### ISSUE THREAD

**Issue by abourget** [inconshreveable/go-update#14]
I get this error:

    rename C:\Users\PB\Desktop\bazooka.exe C:\Users\PB\Desktop\.bazooka.exe.old: The process cannot access the file because it is being used by another process.

which seems to be produced at this line: https://github.com/inconshreveable/go-update/blob/master/update.go#L374

The process is under Windows, running as administrator. Any clues ?

**Comment by abourget** [comment]
This document: http://www.catch22.net/tuts/self-deleting-executables lists `MoveFileEx` as the solution to rename a running file, with the `MOVEFILE_DELAY_UNTIL_REBOOT` flag.. we're using `os.Rename`.. are we sure this is what is called underneath ?

**Comment by abourget** [comment]
that `MOVEFILE_DELAY_UNTIL_REBOOT` isn't the solution.. as the file stays there until a reboot is performed.. we need to zap it out right away.

The only solution I see is to write a `.bat` file that will delete the executable, and rename the `.new` one, and restart the process.. and then kill the current process, after forking the `cmd` for the `.bat` file...

All that seems a bit hairy, but I don't understand how it works on your machines.. it seems to me that Windows can *not* delete or move or rename a running file.

**Comment by inconshreveable** [comment]
So, as far as i understand it, windows can't delete the executable file of a running process. Windows *can* rename the executable file of a running process. See: https://superuser.com/questions/488127/why-can-i-rename-a-running-executable-but-not-delete-it

go-update is cognizant of this. On *nix* systems, go-update deletes the old executable but on Windows we just hide it because of that problem.

If you're encountering an issue where go-update is failing to rename the running executable, it's very likely that your program (or another program) has an open file handle to the executable file.

**Comment by abourget** [comment]
Right.. I think my process does indeed open itself because of `go-rice`... so I'll close this.. I'll find another way.

**Comment by inconshreveable** [comment]
ahhh, that makes a lot of sense. you might try the option where generate the source code files to be included in the binary instead of having them appended as a zipfile. it looks like go-rice supports that. for ngrok I use go-bindata which has been very effective

**Comment by abourget** [comment]
I've got a PR over there to fix the issue. https://github.com/GeertJohan/go.rice/pull/39

thanks :)

**Comment by inconshreveable** [comment]
awesome! thanks for tracking this down!

**Comment by abourget** [comment]
yeah, go.rice supports `http.Filesystem`, so you can navigate through files and not have to list all the files up front (say you add a new .html file after), I recall go-bindata requires you to run some more stuff to pick up the new files..

**Comment by adamgoose** [comment]
@abourget I'm still experiencing this issue. As soon as I comment out any reference to go.rice, renaming the exe works fine. However, when I have go.rice in the app, I get the "in use" error.

My app is a CLI that has a single command to generate an example config file (from the rice box). I try to update inside of another command. It seems strange to me that rice opens the exe even when it's not being utilized.

I trust your PR fixed it back in 2015? Any ideas as to why it's no longer working?

**Comment by adamgoose** [comment]
I've ended up using https://github.com/mjibson/esc instead of rice.
