### ISSUE TITLE
can i get complete example program to understand self update usage? 

### ISSUE THREAD

**Issue by sha-1614** [inconshreveable/go-update#29]

**Comment by frostarun** [comment]
yes that would be helpful , can you provide it ? @inconshreveable

**Comment by inconshreveable** [comment]
The example in the README is pretty much complete. All you'd need to add would be a main function:

``` go
func main() {
  doUpdate("https://example.com/update")
}
```

**Comment by sha-1614** [comment]
Thanks @inconshreveable ,actually i am new to this concept so can you provide any quick startup document to understand it.
