### ISSUE TITLE
Possible to automatically reload itself?

### ISSUE THREAD

**Issue by gust1n** [inconshreveable/go-update#5]
Wouldn't it be cool if go-update also supported automatic reload of the go binary (itself)? I don't know if it's possible or even desirable in the long run it would make the deploy process even smoother, just push a new release and then all nodes running a service would auto update and restart!

**Comment by marbemac** [comment]
I'm very interested in this. However, I'm not sure where to start - could either of you describe, at a high level, how one might build this functionality? Can a binary reload itself?

**Comment by inconshreveable** [comment]
@marbemac It can.

Here's a very simple example: 

```go
import (
	"os"
	"os/exec"
	
	"bitbucket.org/kardianos/osext"
)

func restart() error {
	name, err := osext.Executable()
	if err != nil {
		return err
	}
	return exec.Command(name, os.Args[1:]...).Start()
}
```

Keep in mind that doing this involves cooperation from your application to restart itself. Properly releasing resources or passing them to the new instance, remaining running until all in-progress processes are complete or aborted, etc.

A production-grade solution which can help with this is goagain (which also manages the restarting bit): https://github.com/rcrowley/goagain/

**Comment by inconshreveable** [comment]
Much time and reflection have proven that this kind of feature is out of scope for this package and best located in other packages (like goagain) that focus exclusively on that problem.
